column_width = 160
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
# quote_style = "AutoPreferSingle"
quote_style = "AutoPreferDouble"
# call_parentheses = "None"
call_parentheses = "Always"
