#!/bin/sh
cd $(dirname "$0")

register_file() {
	file="$1"
	[ -z "$file" ] && echo "Error: No file name provided." 1>&2 && return
	[ -h "$HOME/$file" -o ! -e "$HOME/$file" ] && rm -f "$HOME/$file"
	if [ "$file" = ".vim" ]; then
		if [ ! -e "$HOME/$file" ]; then
			ln -s "$PWD" "$HOME/$file"
		fi
	elif [ "$file" = ".vimrc" ]; then
		if [ ! -e "$HOME/$file" ]; then
			ln -s "$PWD/vimrc" "$HOME/$file"
		fi
	else
		if [ ! -e "$HOME/$file" ]; then
			ln -s "$PWD/$file" "$HOME/$file"
		fi
	fi
}

for i in .vim .vimrc; do
	register_file $i
done

if [ ! -e personal.vim ] && [ -e .personal.vim ]; then
	cp -L .personal.vim personal.vim
fi
