#!/bin/sh
set -e
set -u

# CocInstall coc-calc coc-css coc-deno coc-emmet coc-emoji coc-eslint coc-go coc-graphql coc-highlight coc-html coc-json coc-markdownlint coc-omni coc-prettier coc-python coc-rls coc-sh coc-stylelint coc-svelte coc-tag coc-toml coc-tsserver coc-ultisnips coc-vetur coc-vimlsp coc-yaml coc-xml coc-clangd coc-apollo coc-docker
# TSInstall css javascript bash c go html jsdoc json lua python rust toml typescript yaml

/usr/bin/nvim -c 'packloadall|exec "GoUpdateBinaries"|exec "TSInstall all"|exec "TSUpdate"|q'
cd "$(dirname $(readlink -f) "$0")/pack/submodules/start/coc.nvim"
yarn
